;Generate WADE for CP/M 3
;Equate CPM3 in MONOPT.LIB must be TRUE
;
rmac moncpm $$sz pz
rmac monit $$sz pz
rmac monbreak $$sz pz
rmac montab $$sz pz
rmac mondis $$sz pz
rmac monsub $$sz pz
rmac monexpr $$sz pz
rmac monasm $$sz pz
rmac monsym $$sz pz
rmac monpeek $$sz pz
rmac wade $$sz pz
link wade3=wade
link monrsx=moncpm,monit,monbreak,montab,mondis,monsub,monexpr,monasm,monsym,monpeek[op]
era monrsx.rsx
ren monrsx.rsx=monrsx.prl
gencom wade3 monrsx
